# Generated by Django 4.2.1 on 2025-03-26 00:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('application_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('profile_picture', models.ImageField(blank=True, default='profile_pics/default-profile.png', null=True, upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='portal.academicsession')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.department')),
                ('local_government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.lga')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.school')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.semester')),
                ('state_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.state')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.year')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='portal.year'),
        ),
        migrations.AddField(
            model_name='lga',
            name='state_of_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='portal.state'),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.school'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('unit', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.department')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('application_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('profile_picture', models.ImageField(blank=True, default='profile_pics/default-profile.png', null=True, upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.academicsession')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.department')),
                ('local_government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.lga')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.school')),
                ('semester', models.ForeignKey(default=portal.models.get_default_semester, on_delete=django.db.models.deletion.CASCADE, to='portal.semester')),
                ('state_of_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.state')),
                ('year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.year')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('name', 'year')},
        ),
    ]
