# Generated by Django 5.1.7 on 2025-03-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='house_address',
            field=models.CharField(default=1001, max_length=100),
            preserve_default=False,
        ),
    ]
