# Generated by Django 4.2.1 on 2025-04-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredcourse',
            name='year',
        ),
    ]
