# Generated by Django 4.2.1 on 2025-03-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_application_is_approved'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='course',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='department',
        ),
    ]
