# Generated by Django 5.1.7 on 2025-03-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_application_house_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='house_address',
        ),
    ]
