# Generated by Django 4.2.1 on 2025-03-30 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_category_headline_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=10000)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='portal.student')),
            ],
        ),
    ]
