# Generated by Django 4.2.1 on 2025-03-24 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credit_unit',
            new_name='unit',
        ),
    ]
