# Generated by Django 4.2.1 on 2025-03-30 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='student',
        ),
    ]
