# Generated by Django 4.2.1 on 2025-03-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='Headline',
        ),
    ]
