# Generated by Django 5.1.7 on 2025-03-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
