# Generated by Django 5.1.7 on 2025-03-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_application_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='applicant_images/'),
        ),
    ]
