# Generated by Django 5.1.7 on 2025-03-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_application_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='image',
        ),
    ]
